#!/bin/sh
# Script for torrent and samba installation

# // commands that works
# sudo apt-get update
# sudo apt-get install samba -y

sudo mkdir /torrent
sudo mkdir /torrent/Downloaded
sudo mkdir /torrent/Downloading
